server:
    interface: 0.0.0.0
    access-control: 192.168.0.0/24 allow
    
    local-zone: "myjail.local." static
    local-data: "nexus.myjail.local. IN A 192.168.0.51"
    local-data: "freebsd.myjail.local. IN A 192.168.0.50"

forward-zone:
    name: "."
    forward-addr: 8.8.8.8
    forward-addr: 1.1.1.1

